---
title: "FUSO 2023"
author: "Gerko Vink, Anne Scheel and Oisín Ryan"
format: html
---

You can find [our finalized proposal here](Proposal2023_Vink_Scheel_Ryan.pdf)

---

# AI-assisted proposal generation
To generate this proposal, we interacted with [`chatGPT`](https://openai.com/blog/chatgpt/) and [`Perplexity.AI`](https://www.perplexity.ai). Most of the content, references and structure in Box 1 in our proposal has been generated by these AI language models. 

#### Our interaction with `chatGPT`
We have recorded our interaction with `chatGPT`:
{{< video chatGPT_recording.mp4 >}}

#### Our interaction with `Perplexity.AI`
To mimic the procedure adopted with `chatGPT`, we copied and pasted similar prompts from our interaction with `chatGPT` into the `Perplexity.AI` chat window. The prompts to `Perplexity.AI` were slightly shorter and more concise as the 255 character-limit for `Perplexity.AI` did not allow for idential interactions. 

{{< video PerplexityAI_recording.mp4 >}}

#### Transcripts
A transcript of our interactions with the AI language models, including the popular and scientific references proposed by the AI, can be found [here for `chatGPT`](chatGPT_transcript.pdf) and [here for `Perplexity.AI`](PerplexityAI_transcript.pdf)
